# requires docker-compose 1.28.0+
version: '3.9'
services:
  lolminer-amd:
    build:
      context: .
      dockerfile: Dockerfile
    image: compscidr/lolminer:amd-dev
    container_name: lolminer
    devices:
      - /dev/dri:/dev/dri
    entrypoint: /lolminer/lolMiner --coin ETH --pool eth.2miners.com --port 2020 --user 0x74ba897f65f04008d8eff364efcc54b0a20e17eb.nvidia-docker --apihost 0.0.0.0 --apiport 4069
    profiles: ["amd"]
  lolminer-nvidia:
    build:
      context: .
      dockerfile: Dockerfile
    image: compscidr/lolminer:nvidia-dev
    container_name: lolminer
    profiles: ["nvidia"]
    entrypoint: /lolminer/lolMiner --coin ETH --pool eth.2miners.com --port 2020 --user 0x74ba897f65f04008d8eff364efcc54b0a20e17eb.nvidia-docker --apihost 0.0.0.0 --apiport 4069
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
