name: Build containers
on:
  push:

jobs:
  build-nvidia:
    strategy:
      matrix:
        os: [ubuntu20.04,ubuntu22.04]
        cuda: [11.4.2,11.7.1]
        lolminer: [1.52a,1.53,1.54,1.55a,1.56,1.57]
    runs-on: ubuntu-20.04
    name: Build Nvidia Containers
    steps:
      - uses: actions/checkout@v3
      - name: build nvidia image
        run: docker build -f Dockerfile --target nvidia --build-arg LOLMINER_VERSION=${{ matrix.lolminer }} --build-arg OS_VERSION=${{ matrix.os }} --build-arg CUDA_VERSION=${{ matrix.cuda }} -t lolminer-docker:${{ matrix.os }}-cuda-${{ matrix.cuda }}-${{ matrix.lolminer }} .

  build-amd:
    strategy:
      matrix:
        os: [ubuntu20.04,ubuntu22.04]
        amd_driver: ["21.30", "22.20"]
        lolminer: [1.52a,1.53,1.54,1.55a,1.56,1.57]
        exclude:
          - os: ubuntu22.04
            amd_driver: "21.30"
    runs-on: ubuntu-20.04
    name: Build AMD Containers
    steps:
      - uses: actions/checkout@v3
      - name: build amd image
        run: docker build -f Dockerfile --target amd --build-arg LOLMINER_VERSION=${{ matrix.lolminer }} --build-arg OS_VERSION=${{ matrix.os }} --build-arg AMD_DRIVER=${{ matrix.amd_driver }} -t lolminer-docker:${{ matrix.os }}-amd-${{ matrix.amd_driver }}-${{ matrix.lolminer }} .
