name: Build container
on:
  push:

jobs:
  build:
    name: Build container
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: build amd image
        run: docker build -f Dockerfile --target amd -t lolminer-docker:amd-${{ github.sha }} .
      - name: build nvidia image
        run: docker build -f Dockerfile --target nvidia -t lolminer-docker:nvidia-${{ github.sha }} .
