name: Build containers
on:
  push:

jobs:
  build-nvidia:
    strategy:
      matrix:
        os:
          - "ubuntu20.04"
          - "ubuntu22.04"
        cuda:
          - "11.7.1"
          - "12.2.0"
        lolminer:
          - "1.52a"
          - "1.53"
          - "1.54"
          - "1.56"
          - "1.57"
          - "1.58"
          - "1.60"
          - "1.61"
          - "1.62"
          - "1.63"
          - "1.64"
          - "1.65"
          - "1.66"
          - "1.67"
          - "1.69"
          - "1.70"
          - "1.71"
          - "1.72"
          - "1.73"
          - "1.74"
          - "1.75"
          - "1.76"
          - "1.78"
          - "1.79"
          - "1.80"
          - "1.81"
          - "1.82"
          - "1.82a"
          - "1.83"
          - "1.84"
    runs-on: ubuntu-22.04
    name: Build Nvidia Containers
    steps:
      - uses: actions/checkout@v4
      - name: build nvidia image
        run: docker build -f Dockerfile --target nvidia --build-arg LOLMINER_VERSION=${{ matrix.lolminer }} --build-arg OS_VERSION=${{ matrix.os }} --build-arg CUDA_VERSION=${{ matrix.cuda }} -t lolminer-docker:${{ matrix.os }}-cuda-${{ matrix.cuda }}-${{ matrix.lolminer }} .

  build-amd:
    strategy:
      matrix:
        os:
          - "ubuntu20.04"
          - "ubuntu22.04"
        amd_driver:
          - "21.30"
          - "22.20"
        lolminer:
          - "1.52a"
          - "1.53"
          - "1.54"
          - "1.56"
          - "1.57"
          - "1.58"
          - "1.60"
          - "1.61"
          - "1.62"
          - "1.63"
          - "1.64"
          - "1.65"
          - "1.66"
          - "1.67"
          - "1.69"
          - "1.70"
          - "1.71"
          - "1.72"
          - "1.73"
          - "1.74"
          - "1.75"
          - "1.76"
          - "1.78"
          - "1.79"
          - "1.80"
          - "1.81"
          - "1.82"
          - "1.82a"
          - "1.83"
          - "1.84"
        exclude:
          - os: "ubuntu22.04"
          - amd_driver: "21.30"
    runs-on: ubuntu-22.04
    name: Build AMD Containers
    steps:
      - uses: actions/checkout@v4
      - name: build amd image
        run: docker build -f Dockerfile --target amd --build-arg LOLMINER_VERSION=${{ matrix.lolminer }} --build-arg OS_VERSION=${{ matrix.os }} --build-arg AMD_DRIVER=${{ matrix.amd_driver }} -t lolminer-docker:${{ matrix.os }}-amd-${{ matrix.amd_driver }}-${{ matrix.lolminer }} .
