name: Deploy container
on:
  release:
    types:
      - published

jobs:
  deploy:
    name: Deploy container
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: build image
        run: docker build -f Dockerfile -t lolminer-docker:${{ github.sha }} .
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: tag and push
        run: |
        docker tag lolminer-docker:${{ github.sha }} compscidr/lolminer-docker:${{ github.event.release.tag_name }}
        docker push compscidr/lolminer-docker:${{ env.RELEASE_VERSION }}
      - name: Logout of Docker Hub
        run: docker logout
